[package]
name = "anathema"
version = "0.2.0"
edition = "2021"

[dependencies]
anathema-compiler = { path = "./anathema-compiler" }
anathema-render = { path = "./anathema-render" }
anathema-runtime = { path = "./anathema-runtime" }
anathema-vm = { path = "./anathema-vm" }
anathema-widgets = { path = "./anathema-widgets" }
anathema-widget-core = { path = "./anathema-widget-core" }

[workspace.dependencies]
unicode-width = "0.1.10"
crossterm = "0.25.0"
bitflags = "1.3.2"
thiserror = "1.0.40"
flume = "0.10.14"

[workspace]
members = [
    "anathema-compiler",
    "anathema-lsp",
    "anathema-render",
    "anathema-runtime",
    "anathema-vm",
    "anathema-widgets",
    "anathema-widget-core",
]
